#pragma once
// Auto-generated from web_ui.html — do not edit
static const char WEB_UI_HTML[] =
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\n"
    "<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n"
    "<title>QRP Companion</title>\n"
    "<style>\n"
    "*{margin:0;padding:0;box-sizing:border-box}\n"
    "body{background:#000;color:#0f0;font-family:monospace;overflow:hidden;touch-action:none}\n"
    "canvas{display:block;width:100vw;height:100vh}\n"
    "#hud{position:fixed;top:0;left:0;right:0;background:rgba(0,0,80,0.9);padding:6px 10px;font-size:13px;z-index:10;display:flex;justify-content:space-between}\n"
    "#hud span{color:#0f0}\n"
    "#freq{color:#0f0;font-size:16px;font-weight:bold}\n"
    "#btns{position:fixed;bottom:0;left:0;right:0;display:flex;z-index:10}\n"
    "#btns button{flex:1;padding:14px 0;font-family:monospace;font-size:15px;font-weight:bold;border:1px solid #555;background:#222;color:#0ff;touch-action:manipulation}\n"
    "#btns button.active{background:#0ff;color:#000}\n"
    "#btns button.red{color:#f44}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div id=\"hud\">\n"
    "  <span id=\"span\">--</span>\n"
    "  <span id=\"freq\">---.---.---</span>\n"
    "  <span id=\"mode\">---</span>\n"
    "  <span>RTT:<b id=\"rtt\">--</b>ms</span>\n"
    "</div>\n"
    "<canvas id=\"c\"></canvas>\n"
    "<div id=\"btns\">\n"
    "  <button id=\"bSpan\">Span</button>\n"
    "  <button id=\"bFilter\">Filter</button>\n"
    "  <button id=\"bZeroBt\">ZeroBt</button>\n"
    "  <button id=\"bBand\">Band</button>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "const N=512, WF=256, SPEC_FRAC=0.35;\n"
    "const canvas=document.getElementById(\"c\"), ctx=canvas.getContext(\"2d\");\n"
    "let spectrum=new Uint8Array(N), wfBuf=[], vfoFreq=0, mode=0, spanRate=0, apf=false;\n"
    "let rttSamples=[], ws=null;\n"
    "\n"
    "// Color LUT\n"
    "const specColor=i=>{const v=i/255;return v<.5?`rgb(${v*510|0},255,0)`:`rgb(255,${(1-v)*510|0},0)`};\n"
    "const wfLUT=new Array(256);\n"
    "for(let i=0;i<256;i++){\n"
    "  const r=i<85?0:i<170?(i-85)*3:255;\n"
    "  const g=i<85?0:i<170?(i-85)*3:255-(i-170)*3;\n"
    "  const b=i<85?i*3:i<170?255-(i-85)*3:0;\n"
    "  wfLUT[i]=`rgb(${r},${g},${b})`;\n"
    "}\n"
    "\n"
    "function resize(){canvas.width=innerWidth;canvas.height=innerHeight}\n"
    "resize(); addEventListener(\"resize\",resize);\n"
    "\n"
    "function render(){\n"
    "  const W=canvas.width, H=canvas.height;\n"
    "  const btnH=48, hudH=30;\n"
    "  const specH=((H-btnH-hudH)*SPEC_FRAC)|0;\n"
    "  const wfY=hudH+specH+2, wfH=H-btnH-wfY;\n"
    "  const px=W/N;\n"
    "\n"
    "  ctx.fillStyle=\"#000\"; ctx.fillRect(0,0,W,H);\n"
    "\n"
    "  // Spectrum\n"
    "  for(let i=0;i<N;i++){\n"
    "    const v=spectrum[i]/255, bh=(v*specH)|0;\n"
    "    const x=(i*px)|0, bw=Math.max(1,((i+1)*px|0)-(i*px|0));\n"
    "    ctx.fillStyle=specColor(spectrum[i]);\n"
    "    ctx.fillRect(x, hudH+specH-bh, bw, bh);\n"
    "  }\n"
    "\n"
    "  // VFO marker at center (narrow spans) or 3/4 (48k)\n"
    "  const markerX = spanRate>=48000 ? (W*3/4)|0 : (W/2)|0;\n"
    "  ctx.fillStyle=\"rgba(255,255,255,0.7)\";\n"
    "  ctx.fillRect(markerX, hudH, 1, specH);\n"
    "\n"
    "  // Separator\n"
    "  ctx.fillStyle=\"#0f0\"; ctx.fillRect(0, hudH+specH, W, 2);\n"
    "\n"
    "  // Waterfall\n"
    "  const nLines=Math.min(wfBuf.length, (wfH/2)|0);\n"
    "  for(let row=0;row<nLines;row++){\n"
    "    const line=wfBuf[row]; if(!line) continue;\n"
    "    const y=wfY+row*2;\n"
    "    for(let i=0;i<N;i++){\n"
    "      const x=(i*px)|0, bw=Math.max(1,((i+1)*px|0)-(i*px|0));\n"
    "      ctx.fillStyle=wfLUT[line[i]];\n"
    "      ctx.fillRect(x, y, bw, 2);\n"
    "    }\n"
    "  }\n"
    "  requestAnimationFrame(render);\n"
    "}\n"
    "requestAnimationFrame(render);\n"
    "\n"
    "// Format frequency\n"
    "function fmtFreq(f){\n"
    "  if(!f) return \"---.---.---\";\n"
    "  const mhz=(f/1e6)|0, khz=((f%1e6)/1e3)|0, hz=f%1000;\n"
    "  return `${mhz}.${String(khz).padStart(3,'0')}.${String(hz).padStart(3,'0')}`;\n"
    "}\n"
    "const modeStr=m=>({1:\"LSB\",2:\"USB\",3:\"CW\",6:\"DIGI\"}[m]||\"---\");\n"
    "\n"
    "function updateHud(){\n"
    "  document.getElementById(\"freq\").textContent=modeStr(mode)+\" \"+fmtFreq(vfoFreq);\n"
    "  const avg=rttSamples.length?rttSamples.reduce((a,b)=>a+b)/rttSamples.length:0;\n"
    "  document.getElementById(\"rtt\").textContent=avg.toFixed(0);\n"
    "}\n"
    "setInterval(updateHud, 200);\n"
    "\n"
    "// WebSocket\n"
    "function connect(){\n"
    "  const url=`ws://${location.hostname}:${location.port}/ws`;\n"
    "  ws=new WebSocket(url);\n"
    "  ws.binaryType=\"arraybuffer\";\n"
    "  ws.onopen=()=>{\n"
    "    setInterval(()=>{\n"
    "      if(ws.readyState!==1) return;\n"
    "      const b=new ArrayBuffer(9); const v=new DataView(b);\n"
    "      v.setUint8(0,0x10); v.setFloat64(1,performance.now(),true);\n"
    "      ws.send(b);\n"
    "    }, 200);\n"
    "  };\n"
    "  ws.onmessage=e=>{\n"
    "    if(!(e.data instanceof ArrayBuffer)) return;\n"
    "    const v=new DataView(e.data), t=v.getUint8(0);\n"
    "    if(t===0x01 && e.data.byteLength>=23+N){\n"
    "      // Spectrum: type(1) + bins(2) + rate(4) + vfo(8) + mode(1) + apf(1) + pad(6) = 23\n"
    "      spanRate=v.getInt32(3,true);\n"
    "      vfoFreq=Number(v.getBigUint64(7,true));\n"
    "      mode=v.getUint8(15);\n"
    "      apf=!!v.getUint8(16);\n"
    "      spectrum=new Uint8Array(e.data, 23, N);\n"
    "      wfBuf.unshift(spectrum.slice());\n"
    "      if(wfBuf.length>WF) wfBuf.length=WF;\n"
    "      document.getElementById(\"bFilter\").className=apf?\"active\":\"\";\n"
    "    } else if(t===0x11 && e.data.byteLength>=9){\n"
    "      const rtt=performance.now()-v.getFloat64(1,true);\n"
    "      rttSamples.push(rtt);\n"
    "      if(rttSamples.length>20) rttSamples.shift();\n"
    "    }\n"
    "  };\n"
    "  ws.onclose=()=>setTimeout(connect, 1000);\n"
    "  ws.onerror=()=>ws.close();\n"
    "}\n"
    "connect();\n"
    "\n"
    "function sendCmd(buf){if(ws&&ws.readyState===1) ws.send(buf)}\n"
    "\n"
    "function sendTouch(action,x,y){\n"
    "  const W=canvas.width, H=canvas.height;\n"
    "  const b=new ArrayBuffer(11); const v=new DataView(b);\n"
    "  v.setUint8(0,0x20); v.setUint8(1,action);\n"
    "  v.setUint16(2,x|0,true); v.setUint16(4,y|0,true);\n"
    "  v.setUint16(6,W|0,true); v.setUint16(8,H|0,true);\n"
    "  sendCmd(b);\n"
    "}\n"
    "\n"
    "function sendButton(id){\n"
    "  const enc=new TextEncoder();\n"
    "  const name=enc.encode(id);\n"
    "  const b=new Uint8Array(1+name.length);\n"
    "  b[0]=0x30; b.set(name,1);\n"
    "  sendCmd(b.buffer);\n"
    "}\n"
    "\n"
    "// Touch on canvas\n"
    "canvas.addEventListener(\"touchstart\",e=>{e.preventDefault();const t=e.touches[0];sendTouch(0,t.clientX,t.clientY)});\n"
    "canvas.addEventListener(\"touchmove\",e=>{e.preventDefault();const t=e.touches[0];sendTouch(1,t.clientX,t.clientY)});\n"
    "canvas.addEventListener(\"touchend\",e=>{e.preventDefault();sendTouch(2,0,0)});\n"
    "let md=false;\n"
    "canvas.addEventListener(\"mousedown\",e=>{md=true;sendTouch(0,e.clientX,e.clientY)});\n"
    "canvas.addEventListener(\"mousemove\",e=>{if(md)sendTouch(1,e.clientX,e.clientY)});\n"
    "canvas.addEventListener(\"mouseup\",()=>{md=false;sendTouch(2,0,0)});\n"
    "\n"
    "// Buttons\n"
    "document.getElementById(\"bSpan\").onclick=()=>sendButton(\"span\");\n"
    "document.getElementById(\"bFilter\").onclick=()=>sendButton(\"filter\");\n"
    "document.getElementById(\"bZeroBt\").onclick=()=>sendButton(\"zerobt\");\n"
    "document.getElementById(\"bBand\").onclick=()=>sendButton(\"band\");\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n"
;
